site_name: Organization Documentation
theme:
  name: material
  features:
    - navigation.path
    - toc.follow

plugins:
  - search
  - macros:
      modules:
        - macros.main
  - mkdocs-nav-weight

markdown_extensions:
  - toc:
      permalink: "#"
      separator: "_"

# Navigation is driven by mkdocs-nav-weight
nav: []
