site_name: Organization Documentation
theme: material

plugins:
  - search
  - macros:
      modules:
        - macros.main
  - mkdocs-nav-weight

markdown_extensions:
  - toc:
      permalink: "#"
      separator: "_"

# Navigation is driven by mkdocs-nav-weight
nav: []
